sudo: false
language: python
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27-django111-test
  - python: '3.4'
    env: TOXENV=py34-django111-test
  - python: '3.4'
    env: TOXENV=py34-django20-test
  - python: '3.6'
    env: TOXENV=py36-django111-test
  - python: '3.6'
    env: TOXENV=py36-django20-test
  - python: '3.6'
    env: TOXENV=py36-django21-test
  - python: '3.6'
    dist: xenial
    env: TOXENV=py36-django22-test
  - python: '3.6'
    dist: xenial
    env: TOXENV=py36-django30-test
  - python: '3.6'
    dist: xenial
    env: TOXENV=py36-djangomaster-test
  - python: '3.7'
    env: TOXENV=py37-django111-test
  - python: '3.7'
    env: TOXENV=py37-django20-test
  - python: '3.7'
    env: TOXENV=py37-django21-test
  - python: '3.7'
    dist: xenial
    env: TOXENV=py37-django22-test
  - python: '3.7'
    dist: xenial
    env: TOXENV=py37-django30-test
  - python: '3.7'
    dist: xenial
    env: TOXENV=py37-djangomaster-test
  - python: '3.7'
    env: TOXENV=py37-isort
  - python: '3.7'
    env: TOXENV=py37-flake
  allow_failures:
  - env: TOXENV=py36-djangomaster-test
  - env: TOXENV=py37-djangomaster-test
install:
- pip install coveralls tox>=2.1
script:
- tox
after_script:
- coveralls
deploy:
  provider: pypi
  user: djangorequest
  password:
    secure: ihSODos3XjtALjVY8qVDjIeFHfmxjgwABjMmlod4f7IVwf7bST7NLqG0JKPquesNx8mt+1IWdRSTbPKXmhSUqFrgqLts6jKfmj9vtAKKKnKcfNfe548NMC5D5FsYPpRRzX1idUpHxr3O/vo10P2DoQ+b88spmCK/irAtAXvdqd8=
  distributions: sdist bdist_wheel
  on:
    tags: true
